# Generated by Django 6.0.4 on 2026-04-09 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre_cliente', models.CharField(max_length=45)),
                ('apellido_cliente', models.CharField(max_length=45)),
                ('celular_cliente', models.CharField(max_length=20)),
                ('domicilio_cliente', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=50)),
                ('decripcion_servicio', models.TextField(max_length=150)),
                ('precio_servicio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dispoible_servico', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('descripcion_pedido', models.TextField(max_length=100)),
                ('fecha_solicitud_servicio', models.DateField()),
                ('fecha_finalizacion_Servicio', models.DateField()),
                ('estado_pedido', models.CharField(choices=[('PE', 'Draft'), ('EP', 'En progreso'), ('CO', 'Completado')], default='PE', max_length=2)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practica_servicios.cliente')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practica_servicios.servicio')),
            ],
        ),
    ]
