# Generated by Django 6.0.4 on 2026-04-09 22:25

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practica_servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='celular_cliente',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('EP', 'En progreso'), ('CO', 'Completado')], default='PE', max_length=2),
        ),
    ]
