# Generated by Django 6.0.4 on 2026-04-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practica_servicios', '0002_alter_cliente_celular_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='dispoible_servico',
            new_name='disponible_servicio',
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio_servicio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
