# Generated by Django 6.0.4 on 2026-04-09 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practica_servicios', '0003_rename_dispoible_servico_servicio_disponible_servicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id_cliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='id_pedido',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='id_servicio',
        ),
        migrations.AddField(
            model_name='cliente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_solicitud_servicio',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='practica_servicios.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='practica_servicios.servicio'),
        ),
    ]
