# Generated by Django 6.0.4 on 2026-04-09 23:04

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practica_servicios', '0004_remove_cliente_id_cliente_remove_pedido_id_pedido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='id_cliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='id_servicio',
        ),
        migrations.AddField(
            model_name='cliente',
            name='email_cliente',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practica_servicios.cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practica_servicios.servicio'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='celular_cliente',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True),
        ),
    ]
