# Generated by Django 6.0.4 on 2026-04-09 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practica_servicios', '0005_remove_pedido_id_cliente_remove_pedido_id_servicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email_cliente',
        ),
    ]
