# Generated by Django 6.0.4 on 2026-04-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practica_servicios', '0006_remove_cliente_email_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email_cliente',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
